# Generated by Django 3.2.23 on 2024-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='placeholder.png', upload_to='profile_images'),
        ),
    ]
