# Generated by Django 4.2.9 on 2024-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number1',
            field=models.CharField(blank=True, default='08X1111111', max_length=15, null=True),
        ),
    ]
