# Generated by Django 4.2.9 on 2024-02-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_phone_number1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_month',
        ),
    ]
