# Generated by Django 4.2.9 on 2024-02-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_useraddress_options_remove_useraddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(default='BILL', max_length=4),
        ),
    ]
