# Generated by Django 4.2.9 on 2024-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_useraddress_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_id',
            field=models.CharField(default='HOME', editable=False, max_length=4),
        ),
    ]
