# Generated by Django 4.2.9 on 2024-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_useraddress_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_signup',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
