# Generated by Django 4.2.9 on 2024-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_orderlineitem_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
