# Generated by Django 4.2.9 on 2024-02-14 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_delivery_method_order_planned_ship_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received')], default='ORDERED', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('REGPOST', 'RegisteredPost'), ('COLLECT', 'Click & Collect')], default='REGPOST', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='planned_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 19, 33, 51, 294597, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 19, 33, 51, 295243, tzinfo=datetime.timezone.utc)),
        ),
    ]
