# Generated by Django 4.2.9 on 2024-02-15 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_order_planned_ship_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='planned_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 48, 59, 812391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 16, 48, 59, 813107, tzinfo=datetime.timezone.utc)),
        ),
    ]
