# Generated by Django 4.2.9 on 2024-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_orderlineitem_can_be_engraved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='ring_size',
            new_name='product_size',
        ),
    ]
