# Generated by Django 4.2.9 on 2024-02-21 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_rename_ring_size_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'ordering': ['order', 'address_type', 'address_id', 'created_on']},
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_ship_date',
            field=models.DateField(default=datetime.date(2024, 2, 26)),
        ),
    ]
