# Generated by Django 4.2.9 on 2024-02-27 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_product_cat6_value_and_more'),
        ('checkout', '0024_alter_orderlineitem_line_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], default='ORDERED', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_ship_date',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='products.product'),
        ),
    ]
