# Generated by Django 4.2.9 on 2024-03-01 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_alter_orderlineitem_line_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_ship_date',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(choices=[('H', 'Ring size H'), ('I', 'Ring size I'), ('J', 'Ring size J'), ('K', 'Ring size K'), ('L', 'Ring size L'), ('M', 'Ring size M'), ('N', 'Ring size N'), ('O', 'Ring size O'), ('P', 'Ring size P'), ('Q', 'Ring size Q'), ('R', 'Ring size R'), ('S', 'Ring size S'), ('', 'Not set'), ('-', 'Not set')], default='-', max_length=1),
        ),
    ]
