# Generated by Django 4.2.9 on 2024-01-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat5_value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat6_value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cat1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat3',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat4',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='cat5_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cat5'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat6_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cat6'),
        ),
    ]
