# Generated by Django 4.2.9 on 2024-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cat5_cat6_remove_cat1_name_remove_cat2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('nice_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
