# Generated by Django 4.2.9 on 2024-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cat0_product_cat0_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='catname',
            name='default_display',
            field=models.BooleanField(default=True),
        ),
    ]
