# Generated by Django 4.2.9 on 2024-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
