# Generated by Django 4.2.9 on 2024-02-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_useraddress_address_id'),
        ('products', '0010_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
