# Generated by Django 4.2.9 on 2024-02-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dummy_field',
            new_name='promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='hide_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=254),
        ),
    ]
