# Generated by Django 4.2.9 on 2024-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_dummy_field_product_promotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat0_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat1_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat2_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat3_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat4_value',
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Cat0',
        ),
        migrations.DeleteModel(
            name='Cat1',
        ),
        migrations.DeleteModel(
            name='Cat2',
        ),
        migrations.DeleteModel(
            name='Cat3',
        ),
        migrations.DeleteModel(
            name='Cat4',
        ),
    ]
