# Generated by Django 4.2.9 on 2024-02-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_cat0_value_remove_product_cat1_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat6_value',
            new_name='stock_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat5_value',
        ),
    ]
