# Generated by Django 4.2.9 on 2024-02-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_stocktype_alter_product_stock_type_delete_cat6'),
    ]
    migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stocktype'),
        ),

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cat6'),
        ),
    ]
