# Generated by Django 4.2.9 on 2024-02-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_stock_type_cat6_cat6_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_type',
            new_name='cat6_value',
        ),
    ]
