# Generated by Django 4.2.9 on 2024-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cat6_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat6',
            name='default_lead_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktype',
            name='default_lead_time',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
