# Generated by Django 4.2.9 on 2024-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_lead_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_lead_time',
            field=models.IntegerField(default=0),
        ),
    ]
