# Generated by Django 4.2.9 on 2024-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_item_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('STOCK', 'Stocked Item'), ('MTO', 'Make-to-Order'), ('COMM', 'Comission/ One-off'), ('SERV', 'Service'), ('PERS', 'Personalisation')], default='STOCK', max_length=5),
        ),
    ]
