# Generated by Django 4.2.9 on 2024-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ring_size_max',
            field=models.CharField(choices=[('H', 'Ring size H'), ('I', 'Ring size I'), ('J', 'Ring size J'), ('K', 'Ring size K'), ('L', 'Ring size L'), ('M', 'Ring size M'), ('N', 'Ring size N'), ('O', 'Ring size O'), ('P', 'Ring size P'), ('Q', 'Ring size Q'), ('R', 'Ring size R'), ('S', 'Ring size S'), ('', 'Not set')], default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_size_min',
            field=models.CharField(choices=[('H', 'Ring size H'), ('I', 'Ring size I'), ('J', 'Ring size J'), ('K', 'Ring size K'), ('L', 'Ring size L'), ('M', 'Ring size M'), ('N', 'Ring size N'), ('O', 'Ring size O'), ('P', 'Ring size P'), ('Q', 'Ring size Q'), ('R', 'Ring size R'), ('S', 'Ring size S'), ('', 'Not set')], default=' ', max_length=1),
        ),
    ]
