# Generated by Django 4.2.9 on 2024-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_ring_size_max_product_ring_size_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat6_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ring_size_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ring_size_min',
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
