# Generated by Django 4.2.9 on 2024-02-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_product_cat6_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='review_rating',
        ),
    ]
