# Generated by Django 4.2.9 on 2024-03-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_rating_review_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktype',
            name='source',
            field=models.CharField(choices=[('STOCK', 'Stocked Item'), ('MTO', 'Make-to-Order'), ('COMM', 'Comission/ One-off'), ('SERV', 'Service'), ('PERS', 'Personalisation')], default='STOCK', max_length=5),
        ),
    ]
